#!/bin/bash
cd @FOLDER@
cache(){
    gpg --armor --batch --quiet -e -r oli@glow.li > ".cache/$1"
}
prepare(){
    mkdir -p .cache
    rm -f .cache/*||:
    for f in *;do
        (
        ext=${f##*.}
        if [ "$ext" = "gpg" ];then
            data=$(gpg -dq $f)
            filenamewithoutgpg=${f:0:-4}
            ext=${filenamewithoutgpg##*.}
        else
            data=$(<$f)
        fi
        (
        case "$ext" in
            "pmd")
                export data
                data="`php -r "?>${data}"`"
                # Use script to force msee to draw colors
                script -q /dev/null -c 'echo $data|msee'
                ;;
            "md")
                export data
                # Use script to force msee to draw colors
                script -q /dev/null -c 'echo $data|msee'
                ;;
            *)
                echo "$data"
                ;;
        esac
        )|cache $f
        ) &
    done
    wait
}
edit(){
    nvim *
    (
    prepare
    git add * >> .log
    git commit -m "Update on $(date)" > .log
    git push >> .log 2>&1
    )&
}

show(){
    output=""
    for f in *;do
        if [ ! -f ".cache/$f" ];then
            prepare
            break
        fi
    done
    for f in *;do
        output+=`gpg --batch --quiet -d .cache/$f`
    done
    echo "$output"
}
# unlocking gpg, because vim-gpg has problems with input
echo "BEAR"|gpg --quiet -e -r oli@glow.li 2>/dev/null|gpg -d  >/dev/null 2>&1

if [ "$(basename $0)" == "S" ]; then :
    edit
else
    show
fi

